### ISSUE TITLE
Problem with dataset download

### ISSUE THREAD

**Issue by Xiaoshan-jun** [AmeliaCMU/AmeliaScenes#16]
Hi,

I am trying to download the dataset, however, the instruction link is not working. 

Thanks

**Comment by alonsocanov** [comment]
Hi, 

I just updated the [link](https://github.com/AmeliaCMU/AmeliaScenes/blob/main/DATASET.md)

Thank you

**Comment by Xiaoshan-jun** [comment]
Thanks
